require("prototypes/tiles/cobbleStoneTile.lua")
require("prototypes/tiles/dirtStoneTile.lua")
require("prototypes/walls/cobbleStoneWall.lua")
require("prototypes/artifacts/slimeArtifact.lua")
require("prototypes/tiles/artifactSpawnTile.lua")